### ISSUE TITLE
CMIP6 Publisher workflow with respect to PrePARE and CMOR Tables

### ISSUE THREAD

**Issue by SebastienDenvil** [ESGF/esg-publisher#52]
We have been testing CMIP6 publication with CMIP6 test files we produced.
1. The publisher will call PrePARE that will take as input CMOR tables locally installed by the ESGF stack.
2. But if those tables have more than 24 hours of difference with the GitHub CMOR Tables timestamp then the publisher will "git pull" it pull » without any other conditions. 

This is very likely to create conflicts between CMOR tables used to create files and Tables used at publication time.

It is necessary to use CMOR Tables used at time of publication. To that end we can rely on the global attributes "data_specs_version".

**Comment by taylor13** [comment]
I agree this is necessary.   A step will need to be added to or modified in the publication job stream to read the data_specs_version and then obtain the corresponding CMOR tables.  Currently the tables tagged in the github library are those that appear with a new release of CMOR.  Denis says he can add a tag to every updated table version (which are done with each data request release) so that given the data_specs_version number, the publisher can retrieve the corresponding CMOR tables.  Does anyone see any problems with this approach?

**Comment by sashakames** [comment]
to my knowledge this has been corrected and released in master v2.5.9
