### ISSUE TITLE
v2.5.17 publish cmip6 data failure

### ISSUE THREAD

**Issue by chenkangjun** [ESGF/esg-publisher#89]
the error is:
Cannot import handler esgcet.config.cmip6_handler:CMIP6Handler for project cmip6,KeyError: 'esgcet.config.cmip6_handler'", 
thanks any answer.

**Comment by sashakames** [comment]
@chenkangjun  Please try this:  
source /usr/local/conda/bin/activate esgf-pub
conda list | grep cmor

What is returned?

**Comment by chenkangjun** [comment]
No any returened,
Publish CMIP6 data before, Is it to install CMOR first?

**Comment by sashakames** [comment]
That means the cmor python module wasn't set up during the installation.  It's a requirement for cmip6 publication.  We recommend that the model output be run through cmor prior to publication, but this can be done on a cluster rather than the esgf node.

I recommend you re-run the esgf installer, and make sure that you answer 'Y' to the question of whether to install the node for cmip6 as that will set up the cmor module and other associated dependencies.

**Comment by chenkangjun** [comment]
I remember at the time of installation of esg-node is to answer "Y", but I can to try again, Thanks a lot  for you.

**Comment by sashakames** [comment]
@chenkangjun There is a way to manually install the cmor module and dependencies if needed.  however, the assumption is that the installer will handle it and its not needed.

**Comment by chenkangjun** [comment]
after I re-run esg-node install, try to publish cmip6 data, a new error is "esgcet.exceptions.ESGPublishError: Configuration file option missing: mip_era_options in section: project:cmip6, file=/esg/config/esgcet/esg.ini"

**Comment by sashakames** [comment]
You'll need to manually install an updated version of the publisher.   There are instructions on the documentation site  https://esgf.github.io/esg-publisher/installation.html  (use the devel branch) . Also instructions as part of the CDNOT data challenge.  I would coordinate with your CDNOT representative if not you to get the google docs.
